### ISSUE TITLE
设置字体大小

### ISSUE THREAD

**Issue by liwenbus** [praming/Typecho-Theme-Pui#3]
你好，首先感谢你的主题，很好看。
我想请教一下页面最上面的字体要怎么调整大小呢，太小了，就是站点名称、首页、关于等那一行字的，我昨天才刚开始接触博客，不知道怎么弄那些。谢谢你了。

**Comment by praming** [comment]
可以修改下css文件的。如果改全局的话改html类下的字体大小就可以了。

**Comment by liwenbus** [comment]
好的，谢谢哦
